### PR TITLE
Fixing Rover Program Options.

### PR DESCRIPTION
**Pull request by virgilm**

### CODE REVIEW

**Comment by virgilm** [comment]
Errors out when trying to run
solar/virtual_mate.sh | java -jar solarthing.jar "config/base.json"

as in the README...

**Comment by virgilm** [comment]
Trying to play with this project a bit, I find it very hard to get it to work. Any links to what 'virtual mate' is? I am trying to connect to a MPPT solar controller, and I would like to be able to simulate one, which is what this project (also) seems to be doing.

**Comment by retrodaredevil** [comment]
Thanks for taking an interest in the project. 

So the `solar/virtual_mate.sh` file is used to simulate an Outback Mate, for the Outback program. My guess is that you want to do stuff with a Renogy Rover since you submitted this PR you want to do stuff with a Rover.

If you want to simulate a rover, you can look at this: https://github.com/wildmountainfarms/solarthing/blob/master/program/solar/dummy_rover.json. If you define "dummy" in your base config JSON, it will use that instead.

Now that I see your PR, you are correct, that does need to implement ProgramOptions for stuff to work correctly. I did a refactor about two weeks ago and I didn't do enough testing to make sure everything worked perfectly. Thanks for pointing that out. I plan to test your changes and probably merge them tomorrow.

I will update the README to correctly reflect what you need to do if you want to run `solar/virtual_mate.sh | java -jar solarthing.jar "config/base.json"`, as that is for the mate program and `config/base.json` is by default configured for the rover program. I still need to add a quickstart guide for the rover program.

**Comment by retrodaredevil** [comment]
I did a quick check to make sure it built correctly. I want to add some tests to make sure parsing the base.json files work. I'm also going to be adding some more template base.json files and I will remove the base.json file in `program/config`.

Your feedback is helping me improve the documentation, so I really appreciate it.

**Comment by retrodaredevil** [comment]
I did a lot of work on some of the documentation. I also added some more template `base.json` files to `config_templates/base`. You may find https://github.com/wildmountainfarms/solarthing/blob/master/docs/quickstart_rover.md useful.

If you get any more errors, please post the stacktrace and I should be able to help you.

**Comment by virgilm** [comment]
Appreciate the reply and the time you took to update the docs. I have it up and running with couchdb and the dummy rover. My plan is to try it out with another solar controller, e.g. [this one](https://www.amazon.com/OOYCYOO-Controller-Regulator-Blacklight-Lead-Acid/dp/B07T63R5TK/ref=sr_1_4). Any idea if it uses the same protocol?

Not sure if I'm going to go with this project, but I do like the approach of splitting the backend from the front end.

**Comment by retrodaredevil** [comment]
I'm glad you got it working with CouchDB. The CouchDB instance is great if you want to view data in the android app. Otherwise, setting up InfluxDB and Grafana would be what you'd probably want if you wanted to view the data on a nice web interface.

Looking at the OOYCYOO MPPT Charge Controller on Amazon, one of the images shows that it is RS485. Because of this I'm almost certain it does NOT use the same protocol as the Rover. I've seen very few non-Renogy products that use the same protocol and I can't remember any off the top of my head. (They do exist, though)

My guess is that the controller uses a more standard protocol such as the ones found on EPEver MPPT controllers. Something like [epsolar-tracer](https://github.com/kasbert/epsolar-tracer) **might** be compatible with it. I'm not sure, though. I couldn't come up with anything on Google that gave me a definite answer to what protocol that particular CC uses. If you find a manual for that or if you're lucky a serial/modbus communcation document, it would be pretty easy to find what protocl it uses.

**Pull request merged**
